package example.com.lookweather.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import example.com.lookweather.db.bean.City;
import example.com.lookweather.db.bean.Province;
import example.com.lookweather.db.bean.County;

import example.com.lookweather.db.dao.CityDao;
import example.com.lookweather.db.dao.ProvinceDao;
import example.com.lookweather.db.dao.CountyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig provinceDaoConfig;
    private final DaoConfig countyDaoConfig;

    private final CityDao cityDao;
    private final ProvinceDao provinceDao;
    private final CountyDao countyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        provinceDaoConfig = daoConfigMap.get(ProvinceDao.class).clone();
        provinceDaoConfig.initIdentityScope(type);

        countyDaoConfig = daoConfigMap.get(CountyDao.class).clone();
        countyDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        provinceDao = new ProvinceDao(provinceDaoConfig, this);
        countyDao = new CountyDao(countyDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(Province.class, provinceDao);
        registerDao(County.class, countyDao);
    }
    
    public void clear() {
        cityDaoConfig.clearIdentityScope();
        provinceDaoConfig.clearIdentityScope();
        countyDaoConfig.clearIdentityScope();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public ProvinceDao getProvinceDao() {
        return provinceDao;
    }

    public CountyDao getCountyDao() {
        return countyDao;
    }

}
